import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {launchBrowser,artifactURL,outputPath} from './browser-support.mjs';
const browser=await launchBrowser();
const errors=[],requests=[];
try{
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
  await context.route('https://**/*',route=>{requests.push(route.request().url());return route.abort();});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto(artifactURL);
  await page.waitForSelector('.graph-node');
  assert.equal(await page.locator('.graph-node').count(),1);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:outputPath('tangle-phone-initial.png'),fullPage:true});
  await page.click('#run');
  await page.waitForFunction(()=>document.getElementById('status').textContent==='Root resolved',{},{timeout:45000});
  assert.equal(await page.locator('.graph-node').count(),9);
  assert.equal(requests.length,0,'Simulation must not contact the network');
  await page.click('#fit');
  await page.screenshot({path:outputPath('tangle-phone-grown.png'),fullPage:true});
  const downloadPromise=page.waitForEvent('download');await page.click('#export');const download=await downloadPromise;
  const exported=JSON.parse(await readFile(await download.path(),'utf8'));
  assert.equal(exported.nodes[0].status,'resolved');assert.equal(exported.visits,13);
  await page.click('#liveMode');assert.equal(await page.locator('.graph-node').count(),1);assert.equal(await page.locator('#run').isDisabled(),true);
  await page.click('#simMode');assert.equal(await page.locator('.graph-node').count(),9);
  await page.selectOption('#scenario','blocked');await page.click('#run');
  await page.waitForFunction(()=>document.getElementById('status').textContent.includes('No runnable nodes'),{},{timeout:45000});
  assert.equal(await page.locator('.graph-node[data-status=blocked]').count(),1);
  await page.selectOption('#scenario','repeat');await page.click('#run');
  await page.waitForFunction(()=>document.getElementById('status').textContent.includes('Paused on error'),{},{timeout:30000});
  assert.equal(await page.locator('.graph-node').count(),7);
  await page.selectOption('#scenario','revisit');await page.click('#run');await page.waitForTimeout(100);await page.click('#stop');
  await page.waitForFunction(()=>document.getElementById('step').disabled===false);
  assert.ok((await page.locator('#status').textContent()).includes('Stopped'));
  await page.click('#reset');await page.click('#step');await page.waitForFunction(()=>document.querySelectorAll('.graph-node').length===4);
  assert.equal(await page.locator('#step').isEnabled(),true);
  await page.click('#liveMode');await page.click('#checkDevice');
  await page.waitForFunction(()=>!document.getElementById('deviceStatus').textContent.includes('Checking'),{},{timeout:10000});
  console.log('Capability probe:',await page.locator('#deviceStatus').textContent());
  await page.click('#simMode');await page.click('#fit');
  await page.setViewportSize({width:320,height:780});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:outputPath('tangle-phone-320.png'),fullPage:true});
  await page.setViewportSize({width:1280,height:900});await page.click('#run');
  await page.waitForFunction(()=>document.getElementById('status').textContent==='Root resolved',{},{timeout:45000});await page.click('#fit');
  await page.screenshot({path:outputPath('tangle-desktop.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:outputPath('tangle-dark.png'),fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS: file:// startup, zero-network simulation, 3 scenarios, stop, one-step, export, mode isolation, device probe, 320/390/1280 layouts, dark theme.');
}finally{await browser.close();}
