import assert from 'node:assert/strict';
import {launchBrowser,artifactURL,outputPath} from './browser-support.mjs';
const browser=await launchBrowser();
try{
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto(artifactURL);
  await page.click('#run');await page.waitForTimeout(120);await page.click('#run');
  await page.waitForFunction(()=>!document.getElementById('step').disabled);
  const paused=await page.locator('.graph-node').count();await page.waitForTimeout(900);
  assert.equal(await page.locator('.graph-node').count(),paused);
  await page.click('#fit');
  const child=page.locator('.graph-node[data-id=n2]');await child.tap();
  assert.match(await page.locator('#nodeId').textContent(),/^n2/);
  const before=await page.locator('#world').getAttribute('style');await page.click('#zoomIn');
  assert.notEqual(await page.locator('#world').getAttribute('style'),before);
  const rect=await page.locator('#map').boundingBox();
  await page.mouse.move(rect.x+30,rect.y+30);await page.mouse.down();await page.mouse.move(rect.x+80,rect.y+100,{steps:5});await page.mouse.up();
  assert.equal(await page.locator('#follow').isChecked(),false);
  const {createRun}=await import('../src/core.js');
  const safe=createRun('<img src=x onerror=alert(1)>','simulation');
  await page.setInputFiles('#importFile',{name:'safe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(safe))});
  await page.waitForFunction(()=>document.getElementById('status').textContent.includes('inspection')||document.getElementById('status').textContent.includes('inspect-only'));
  assert.equal(await page.locator('#nodeQuestion img').count(),0);
  assert.equal(await page.locator('#nodeQuestion').textContent(),safe.seed);
  assert.equal(await page.locator('#run').isDisabled(),true);
  const bad=createRun('seed','simulation');bad.evidence.push({id:'e1',title:'evil',kind:'wiki',text:'bad',url:'javascript:alert(1)'});
  await page.setInputFiles('#importFile',{name:'unsafe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});
  await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Import rejected'));
  assert.equal(await page.locator('#nodeQuestion').textContent(),safe.seed);
  await page.click('#simMode');assert.equal(await page.locator('.graph-node').count(),paused);
  await page.click('#liveMode');
  await page.evaluate(()=>Object.defineProperty(navigator,'gpu',{value:undefined,configurable:true}));
  await page.click('#loadModel');
  await page.waitForFunction(()=>document.getElementById('loadStatus').textContent.startsWith('Could not load'));
  assert.match(await page.locator('#loadStatus').textContent(),/No usable WebGPU/);
  await page.click('#simMode');assert.equal(await page.locator('#run').isEnabled(),true);
  assert.deepEqual(errors,[]);
  console.log('PASS: pause, touch node selection, zoom/pan, inspect-only import, XSS-as-text, unsafe URL rejection, preserved sessions, no-GPU load failure and simulation recovery.');
}finally{await browser.close();}
